name: Demo CI/CD med Python

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev"]

jobs:
  # hitta på ett namn på ditt jobb
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Hämta koden
      - name: Checka ut koden från repot
        uses: actions/checkout@v7

      # 2. Installera Python
      - name: Inställningar för Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      # 3. Installera beroenden (pytest m.m.)
      - name: Installera beroenden
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      # 4. Linting
      - name: Linta koden med flake8
        run: flake8 src tests

      # 5. Kör tester (tips: använd markers)
      - name: Kör testerna med pytest
        run: pytest --maxfail=1 --disable-warnings -q

# För CD behöver vi lägga till flera steg
